config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'reports',                             to: 'iepcreports#index',    as: 'reportes'

get 'reports/activity',                    to: 'iepcreports#activity', as: 'reporteActividades'
get 'reports/:del/:al/:id/activity',       to: 'iepcreports#activity', as: 'reporteActividadesConFecha'

get 'reports/calendar',                    to: 'iepcreports#calendar', as: 'reporteCalendario'
get 'reports/calendar/:del/:al/:id',       to: 'iepcreports#calendar', as: 'reporteCalendarioConFecha'

get 'reports/calendar/excel',              to: 'iepcreports#calendar', as: 'reporteCalendarioExcel'
get 'reports/calendar/:del/:al/:id/excel', to: 'iepcreports#calendar', as: 'reporteCalendarioConFechaExcel'

app/controllers/iepcreports_controller.rb
class IepcreportsController < ApplicationController
  menu_item :activity
  before_filter :find_optional_project, :set_as_private
  accept_rss_auth :index
  require 'date'
  require 'axlsx'
  include ActionView::Helpers::TextHelper

  def index

  end

  def set_as_private
    expires_now
  end

  def activity
    @allprojects = Project.all


    projects_by_id = {}
    @allprojects.each do |project|
      projects_by_id[project.id] = project.identifier
    end
    today = Date.today;

    @date_from = params[:del].nil? ? (today.at_beginning_of_week) : (Date.parse params[:del])
    @date_to   = params[:al].nil? ? (today.at_end_of_week) : (Date.parse params[:al])
    @direccion = params[:id].nil? ? 'direccion-general' : params[:id]

    @author = (params[:user_id].blank? ? nil : User.active.find(params[:user_id]))

    @activity = Redmine::Activity::Fetcher.new(User.current,
                                               :project => @project,
                                               :with_subprojects => 1,
                                               :author => @author)
    @activity.default_scope!
    events = @activity.events(@date_from, @date_to)
    @events_by_day = events.group_by {|event| event.attributes['project_id']}

    @events_by_day = @events_by_day.sort_by {|key, issue| key.nil? ? 'a' : projects_by_id[key] }

  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def outdatedCalendar
    @allprojects = Project.all

    projects_by_id = {
        1 => -2,   # Programa Operativo Anual
        2 => -1,   # Secretaría Ejecutiva
        3 => 0,   # Dirección General
        4 => 1,   # Administración y finanzas
        5 => 2,   # Capacitación Electoral
        6 => 3,   # Informática
        7 => 4,   # Jurídico
        8 => 5,   # Organización
        9 => 12,  # Fiscalización
        10 => 6,  # Comunicación Social
        11 => 7,  # Participación ciudadana
        12 => 8,  # Secretaría Técnica
        13 => 9,  # Transparencia
        14 => 10, # Unidad Editorial
        15 => 11, # Prerrogativas
        16 => 13, # Contraloría
        17 => 14, # Presidencia
        18 => 15  # Consejo General
    }

    #@allprojects.each do |project|
    #  projects_by_id[project.id] = project.identifier
    #end

    nextweek   = Date.today.at_end_of_week + 2
    direccion  = params[:id].nil? ? 'direccion-general' : params[:id]

    @date_from = params[:del].nil? ? (nextweek.at_beginning_of_week) : (Date.parse params[:del])
    @date_to   = params[:al].nil? ? (nextweek.at_end_of_week) : (Date.parse params[:al])
    @direccion = Project.find_by_identifier direccion
    @author    = (params[:user_id].blank? ? nil : User.active.find(params[:user_id]))

    direcciones = [@direccion.id]
    @direccion.children.each do |subdireccion|
      direcciones.push subdireccion.id
    end

    @issues = Issue.open
                   .where('project_id in (' + direcciones.join(', ') + ')')
                   .where('(start_date <= ? and done_ratio < 100) or (start_date <= ? and start_date >= ?)', @date_to, @date_to, @date_from)
                   .where('tracker_id not in (4,5)')
                   .order('start_date DESC')
                   .group_by {|issue| issue.attributes['project_id']}

    @issues = @issues.sort_by {|key, issue| projects_by_id[key] }

    if request.fullpath.index('excel')
      Axlsx::Package.new do |p|
        wb = p.workbook
        wb.styles do |s|
          heading1    = s.add_style alignment: {horizontal: :center}, b: true, sz: 12, bg_color: 'FFFFFF', fg_color: '000000'
          heading3    = s.add_style alignment: {horizontal: :left}, b: true, sz: 11, bg_color: 'FFFFFF', fg_color: '000000'
          descripcion = s.add_style :alignment => {wrap_text: true}
          date = s.add_style(:format_code => 'yyyy-mm-dd', :b => true, alignment: {horizontal: :left})
          padded = s.add_style(:format_code => '00#')
          percent = s.add_style(:format_code => '0000%')

          wb.add_worksheet(:name => 'Agenda de actividades') do |sheet|
            sheet.add_row ['Agenda de actividades del ' + @date_from.to_s + ' al ' + @date_to.to_s], style: heading1
            sheet.merge_cells("A#{sheet.rows.length}:D#{sheet.rows.length}")
            sheet.add_row []

            @issues.each do |key, project|
              sheet.add_row [@allprojects[key-1]], :style => heading3
              sheet.merge_cells("A#{sheet.rows.length}:D#{sheet.rows.length}")
              project.each do |issue|
                sheet.add_row [issue.done_ratio.to_s + '%', '[' + issue.id.to_s + ']', issue.start_date, truncate(issue.event_title.partition(':')[2], :length => 140)], :style => [percent, padded, date, padded]
                if issue.description.length > 0
                  sheet.add_row [nil,nil,issue.description], :style => descripcion
                  sheet.merge_cells("C#{sheet.rows.length}:D#{sheet.rows.length}")
                end
              end
              sheet.add_row []
            end

            sheet.column_widths 8, 10, 12, 140
          end

        end
        p.serialize("#{Rails.root}/tmp/agenda_actividades.xlsx")
      end
      send_file "#{Rails.root}/tmp/agenda_actividades.xlsx", :type => "application/xlsx", :x_sendfile => true
    end

  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def calendar
    projects_by_id = {
        1 => -2,   # Programa Operativo Anual
        2 => -1,   # Secretaría Ejecutiva
        3 => 0,   # Dirección General
        4 => 1,   # Administración y finanzas
        5 => 2,   # Capacitación Electoral
        6 => 3,   # Informática
        7 => 4,   # Jurídico
        8 => 5,   # Organización
        9 => 12,  # Fiscalización
        10 => 6,  # Comunicación Social
        11 => 7,  # Participación ciudadana
        12 => 8,  # Secretaría Técnica
        13 => 9,  # Transparencia
        14 => 10, # Unidad Editorial
        15 => 11, # Prerrogativas
        16 => 13, # Contraloría
        17 => -3, # Presidencia
        18 => -4  # Consejo General
    }
    nextweek         = Date.today.at_end_of_week + 2
    direccion_param  = params[:id].nil? ? 'direccion-general' : params[:id]
    @date_from       = params[:del].nil? ? (nextweek.at_beginning_of_week) : (Date.parse params[:del])
    @date_to          = params[:al].nil? ? (nextweek.at_end_of_week) : (Date.parse params[:al])

    @allprojects = Project.all
      .delete_if {|project| projects_by_id[project.id] < 0}
      .sort_by {|project| projects_by_id[project.id]}

    @direccion = Project.find_by_identifier direccion_param
    @direcciones = [@direccion]
    @direccion.children.each do |subdireccion|
      @direcciones.push subdireccion
    end
    @direcciones.sort_by {|project| projects_by_id[project.id]}

    @direcciones_y_tareas = {}

    @direcciones.each do |project|
      @direcciones_y_tareas[project] = Issue.open
        .where('project_id = ?', project.id)
        .where('parent_id IS NULL')
        .where('(start_date <= ? and done_ratio < 100) or (start_date <= ? and start_date >= ?)', @date_to, @date_to, @date_from)
        .order('start_date DESC')
    end

  rescue ActiveRecord::RecordNotFound
    render_404
  end

  private

  def find_optional_project
    return true unless params[:id]
    @project = Project.find(params[:id])
    authorize
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/helpers/iepcreports_helper.rb
module IepcreportsHelper
  include ActionView::Helpers::UrlHelper

  def sort_activity_events(events)
    events_by_group = events.group_by(&:event_group)
    sorted_events = []
    events.sort {|x, y| y.event_datetime <=> x.event_datetime}.each do |event|
      if group_events = events_by_group.delete(event.event_group)
        group_events.sort {|x, y| y.event_datetime <=> x.event_datetime}.each_with_index do |e, i|
          sorted_events << [e, i > 0]
        end
      end
    end
    sorted_events
  end

  def format_report_activity_title(text)
    h(truncate_single_line(text.partition(':')[2], :length => 140))
  end

  def print_issue_report(issue)
    trackers = {
        4 => 'AP',
        5 => 'AI',
        6 => 'A',
        2 => 'T',
        7 => 'E'
    }

    '<li class="issue">' +
      '<input type="checkbox">' +
      '<span class="done_ratio">' + issue.done_ratio.to_s + '%' + '</span>' +
      '<span class="link">[' + link_to(issue.id.to_s + '-' + trackers[issue.tracker_id], issue.event_url) + ']</span>' +
      '<strong>' + issue.start_date.to_s + '</strong>' +
      link_to(format_report_activity_title(issue.event_title), issue.event_url) +
      '<div class="description">' + issue.description + '</div>' +
    '</li>'
  end

  def print_issues_report(issues, date_from, date_to)
    print = String.new

    print += '<ul class="expanded">'
    issues.each do |issue|
      if (!issue.start_date.nil?) && ((issue.done_ratio < 100 && issue.start_date <= date_from) || (issue.start_date <= date_to and issue.start_date >= date_from))
        print += print_issue_report issue
        if issue.children.any?
          print += print_issues_report issue.children, date_from, date_to
        end
      end
    end
    print += '</ul>'
  end

end

app/views/iepcreports/activity.html.erb
<h2><%= link_to 'Reportes', reportes_path %>: Actividades semanales</h2>

<hr>
<label><strong>Del</strong> <input id="fechaReporteDel" type="date" value="<%= @date_from %>"></label>
<label> <strong>al</strong> <input id="fechaReporteAl" type="date" value="<%= @date_to %>"></label>

<select id="projects">
  <% @allprojects.each do |project| %>
      <option <%= 'selected' if project.identifier == @direccion %> value="<%= project.identifier %>"><%= project %></option>
  <% end %>
</select>

<button type="button" id="botonVerReporte">Ver</button>
<hr>

<h2><%= @author.nil? ? l(:label_activity) : l(:label_user_activity, link_to_user(@author)).html_safe %></h2>

<p class="subtitle"><%= l(:label_date_from_to, :start => format_date(@date_from ), :end => format_date(@date_to)) %></p>

<div id="activity">
  <% @events_by_day.each do |key, day| %>
      <% if key %>
          <h3><%= @allprojects[key-1] %></h3>
          <table cellspacing="0">
            <% day.each do |e| -%>
                <tr>
                  <td><%= e.done_ratio %>%</td>
                  <td>[<%= link_to e.id, e.event_url %>] </td>
                  <td><%= link_to format_report_activity_title(e.event_title), e.event_url %></td>
                </tr>
            <% end -%>
          </table>
      <% end %>
  <% end -%>
</div>

<% content_for :header_tags do %>
    <%= auto_discovery_link_tag(:atom, params.merge(:format => 'atom', :from => nil, :key => User.current.rss_key)) %>
<% end %>

<% content_for :sidebar do %>

<% end %>

<% html_title(l(:label_activity), @author) -%>

<script>
  $(function(){
    $("#botonVerReporte").click(function(){
        var fechaDel = $("#fechaReporteDel").val(),
            fechaAl  = $("#fechaReporteAl").val(),
            project  = $("#projects").val();

        window.location.pathname = "reports/" + fechaDel + "/" + fechaAl + "/" + project + "/activity";
    });
  });
</script>

app/views/iepcreports/calendar.html.erb
<h2><%= link_to 'Reportes', reportes_path %>: Agenda de actividades</h2>

<style>
  #calendarReport li.issue {
      border-bottom: 1px solid #dddddd;
  }
  #calendarReport li.issue .done_ratio{
      margin-right: 1em;
  }
  #calendarReport li.issue .link {
      display: inline-block;
      min-width: 4em;
      text-align: center;
  }
  #calendarReport li.issue strong {
      margin: 0 1em;
  }
  #calendarReport div.description {
      padding: 0.2em 0.5em;
  }

  ul ul {
      display: none;
  }
  ul.expanded {
      display: block;
  }
  li.expansible {
      cursor: pointer;
  }
  li.expansible .link, li.expansible .done_ratio {
      font-weight: bold;
  }
  li.expansible strong {
      text-decoration: underline;
  }
  #statusbar button{
      float: right;
  }
</style>

<hr>
<label><strong>Del</strong> <input id="fechaReporteDel" type="date" value="<%= @date_from %>"></label>
<label> <strong>al</strong> <input id="fechaReporteAl" type="date" value="<%= @date_to %>"></label>

<select id="projects">
  <% @allprojects.each do |project| %>
      <option <%= 'selected' if project.id == @direccion.id %> value="<%= project.identifier %>"><%= project %></option>
  <% end %>
</select>

<button type="button" id="botonVerReporte">Ver</button>
<hr>

<fieldset id="statusbar">
  <button type="button" id="botonExpandir" title="Expandir">+++</button>
  <button type="button" id="botonColapsar" title="Colapsar">---</button>
  <b>AP</b>: Actividad programada, <b>AI</b>: Actividad institucional, <b>A</b>: Actividad, <b>T</b>: Tarea, <b>E</b>: Evento
</fieldset>

<h2><%= l(:label_activity) %></h2>

<p class="subtitle"><%= l(:label_date_from_to, :start => format_date(@date_from ), :end => format_date(@date_to)) %></p>

<div id="calendarReport">
  <% @direcciones_y_tareas.each do |direccion, issues| %>
    <h3><%= direccion %></h3>
    <%= raw(print_issues_report(issues, @date_from, @date_to)) %>
  <% end %>
</div>
<div style="text-align: center;">
  <!--<button id="descargarenexcel" type="button">Descargar en excel</button>-->
</div>
<br>

<% content_for :header_tags do %>
    <%= auto_discovery_link_tag(:atom, params.merge(:format => 'atom', :from => nil, :key => User.current.rss_key)) %>
<% end %>

<% content_for :sidebar do %>

<% end %>

<% html_title(l(:label_activity)) -%>

<script>
    $(function(){
        var $calendarReport = $("#calendarReport");

        $("#botonVerReporte").click(function(){
            var fechaDel = $("#fechaReporteDel").val(),
                    fechaAl  = $("#fechaReporteAl").val(),
                    project  = $("#projects").val();

            window.location.pathname = "reports/calendar/" + fechaDel + "/" + fechaAl + "/" + project;
        });

        $calendarReport.find("ul").each(function(index, element) {
            $(element).prev("li").addClass("expansible");
        });

        $calendarReport.find("li").click(function(){
            var $li = $(this);

            if ($(event.target).is("input")) {
                return;
            }

            $li.next("ul").toggleClass("expanded");
        });

        $("#botonExpandir").click(function(){
            $calendarReport.find("ul").addClass("expanded");
        });
        $("#botonColapsar").click(function(){
            $calendarReport.find("ul").removeClass("expanded");
        });

        $("#descargarenexcel").click(function(){
            window.location.pathname = window.location.pathname + "/excel";
        });
    });
</script>

app/views/iepcreports/index.html.erb
<h2>Reportes</h2>
<ul>
  <li>
    <%= link_to 'Actividades semanales', reporteActividades_path %>
  </li>
  <li>
    <%= link_to 'Agenda de actividades', reporteCalendario_path %>
  </li>
</ul>

app/views/iepcreports/obsoeltecalendar.html.erb
<h2><%= link_to 'Reportes', reportes_path %>: Agenda de actividades</h2>

<hr>
<label><strong>Del</strong> <input id="fechaReporteDel" type="date" value="<%= @date_from %>"></label>
<label> <strong>al</strong> <input id="fechaReporteAl" type="date" value="<%= @date_to %>"></label>

<select id="projects">
  <% @allprojects.each do |project| %>
      <option <%= 'selected' if project.id == @direccion.id %> value="<%= project.identifier %>"><%= project %></option>
  <% end %>
</select>

<button type="button" id="botonVerReporte">Ver</button>
<hr>

<h2><%= l(:label_activity) %></h2>

<p class="subtitle"><%= l(:label_date_from_to, :start => format_date(@date_from ), :end => format_date(@date_to)) %></p>

<div id="activity">
  <% @issues.each do |key, day| %>
      <% if key %>
          <h3><%= @allprojects[key-1] %></h3>
          <table cellspacing="0">
            <% day.each do |e| -%>
                <tr>
                  <td><%= e.done_ratio %>%</td>
                  <td>[<%= link_to e.id, e.event_url %>] </td>
                  <td><strong><%= e.start_date %></strong></td>
                  <td><%= link_to format_report_activity_title(e.event_title), e.event_url %></td>
                </tr>
                <tr>
                  <td colspan="2">
                    &nbsp;
                  </td>
                  <td colspan="2">
                    <%= e.description %>
                  </td>
                </tr>
            <% end -%>
          </table>
          <hr>
      <% end %>
  <% end -%>
</div>
<div style="text-align: center;">
  <button id="descargarenexcel" type="button">Descargar en excel</button>
</div>
<br>

<% content_for :header_tags do %>
    <%= auto_discovery_link_tag(:atom, params.merge(:format => 'atom', :from => nil, :key => User.current.rss_key)) %>
<% end %>

<% content_for :sidebar do %>

<% end %>

<% html_title(l(:label_activity)) -%>

<script>
    $(function(){
        $("#botonVerReporte").click(function(){
            var fechaDel = $("#fechaReporteDel").val(),
                    fechaAl  = $("#fechaReporteAl").val(),
                    project  = $("#projects").val();

            window.location.pathname = "reports/calendar/" + fechaDel + "/" + fechaAl + "/" + project;
        });

        $("#descargarenexcel").click(function(){
            window.location.pathname = window.location.pathname + "/excel";
        });
    });
</script>